name = "g"
main = "src/index.js"
compatibility_date = "2025-08-10"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = true

[[d1_databases]]
binding = "DB"
database_name = "ruen-aksorn"
database_id = "a90ace59-0b0f-4559-9878-d7643e61451c"

[[durable_objects.bindings]]
name = "CHAT"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
invocation_logs = true
persist = true
head_sampling_rate = 1
